export * from './ArrowBackButtonSVG';
export * from './ArrowBackSVG';
export * from './ChatFilledSVG';
export * from './ConfettiSVG';
export * from './GoogleSVG';
export * from './LocationSVG';
export * from './NotificationSVG';
export * from './OrderSVG';
export * from './PhoneOutlineSVG';
export * from './SupportSVG';
export { default as BackArrowIcon } from './BackArrowIcon';
export { default as VerifiedIcon } from './VerifiedIcon';
