export * from './ArrowBackButtonSVG';
export * from './ArrowBackSVG';
export * from './ChatFilledSVG';
export * from './CompletedOrdersSVG';
export * from './ConfettiSVG';
export * from './CustomersSVG';
export * from './EarningsWalletSVG';
export * from './GoogleSVG';
export * from './LocationSVG';
export * from './MyShoppersSVG';
export * from './NotificationSVG';
export * from './OrderSVG';
export * from './PhoneOutlineSVG';
export * from './ResourcesSVG';
export * from './SettingsSVG';
export * from './StoreSVG';
export * from './SupportSVG';
export * from './TransactionsSVG';
export { default as BackArrowIcon } from './BackArrowIcon';
export { default as VerifiedIcon } from './VerifiedIcon';
