/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Content } from '../models';
// @ts-ignore
import type { ContentType } from '../models';
// @ts-ignore
import type { UpdateContentPayload } from '../models';
/**
 * ContentApi - axios parameter creator
 */
export const ContentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves the content for a given type, such as PRIVACY_POLICY. This is a public endpoint.
         * @summary Get static content by type
         * @param {ContentType} type The type of content to retrieve.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentTypeGet: async (type: ContentType, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('contentTypeGet', 'type', type)
            const localVarPath = `/content/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates or updates the content for a given type. Requires admin privileges. The content should be an HTML string.
         * @summary Update static content by type (Admin)
         * @param {UpdateContentPayload} updateContentPayload 
         * @param {ContentType} type The type of content to update.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentTypePatch: async (updateContentPayload: UpdateContentPayload, type: ContentType, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateContentPayload' is not null or undefined
            assertParamExists('contentTypePatch', 'updateContentPayload', updateContentPayload)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('contentTypePatch', 'type', type)
            const localVarPath = `/content/{type}`
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateContentPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContentApi - functional programming interface
 */
export const ContentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContentApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves the content for a given type, such as PRIVACY_POLICY. This is a public endpoint.
         * @summary Get static content by type
         * @param {ContentType} type The type of content to retrieve.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentTypeGet(type: ContentType, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Content>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentTypeGet(type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentTypeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates or updates the content for a given type. Requires admin privileges. The content should be an HTML string.
         * @summary Update static content by type (Admin)
         * @param {UpdateContentPayload} updateContentPayload 
         * @param {ContentType} type The type of content to update.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentTypePatch(updateContentPayload: UpdateContentPayload, type: ContentType, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Content>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentTypePatch(updateContentPayload, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentTypePatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ContentApi - factory interface
 */
export const ContentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContentApiFp(configuration)
    return {
        /**
         * Retrieves the content for a given type, such as PRIVACY_POLICY. This is a public endpoint.
         * @summary Get static content by type
         * @param {ContentType} type The type of content to retrieve.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentTypeGet(type: ContentType, options?: RawAxiosRequestConfig): AxiosPromise<Content> {
            return localVarFp.contentTypeGet(type, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates or updates the content for a given type. Requires admin privileges. The content should be an HTML string.
         * @summary Update static content by type (Admin)
         * @param {UpdateContentPayload} updateContentPayload 
         * @param {ContentType} type The type of content to update.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentTypePatch(updateContentPayload: UpdateContentPayload, type: ContentType, options?: RawAxiosRequestConfig): AxiosPromise<Content> {
            return localVarFp.contentTypePatch(updateContentPayload, type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContentApi - object-oriented interface
 */
export class ContentApi extends BaseAPI {
    /**
     * Retrieves the content for a given type, such as PRIVACY_POLICY. This is a public endpoint.
     * @summary Get static content by type
     * @param {ContentType} type The type of content to retrieve.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public contentTypeGet(type: ContentType, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentTypeGet(type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates or updates the content for a given type. Requires admin privileges. The content should be an HTML string.
     * @summary Update static content by type (Admin)
     * @param {UpdateContentPayload} updateContentPayload 
     * @param {ContentType} type The type of content to update.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public contentTypePatch(updateContentPayload: UpdateContentPayload, type: ContentType, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentTypePatch(updateContentPayload, type, options).then((request) => request(this.axios, this.basePath));
    }
}

