/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DashboardAovGet200Response } from '../models';
// @ts-ignore
import type { DashboardCardsGet200Response } from '../models';
// @ts-ignore
import type { DashboardStatsGet200Response } from '../models';
// @ts-ignore
import type { DashboardTransactionsGet200Response } from '../models';
/**
 * DashboardApi - axios parameter creator
 */
export const DashboardApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Calculates the average order value for the specified timeframe.
         * @summary Get average order value (Admin)
         * @param {DashboardAovGetTimeframeEnum} [timeframe] The timeframe filter.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardAovGet: async (timeframe?: DashboardAovGetTimeframeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dashboard/aov`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (timeframe !== undefined) {
                localVarQueryParameter['timeframe'] = timeframe;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves total counts for users, stores, orders, and delivered orders.
         * @summary Get dashboard card metrics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardCardsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dashboard/cards`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves statistics like new customers, new stores, stock status, items sold, and revenue for a specific timeframe.
         * @summary Get dashboard statistics for a timeframe (Admin)
         * @param {DashboardStatsGetTimeframeEnum} [timeframe] The timeframe for the statistics.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardStatsGet: async (timeframe?: DashboardStatsGetTimeframeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dashboard/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (timeframe !== undefined) {
                localVarQueryParameter['timeframe'] = timeframe;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a list of recent transactions within the specified timeframe.
         * @summary Get recent transactions (Admin)
         * @param {DashboardTransactionsGetTimeframeEnum} [timeframe] The timeframe filter.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardTransactionsGet: async (timeframe?: DashboardTransactionsGetTimeframeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dashboard/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (timeframe !== undefined) {
                localVarQueryParameter['timeframe'] = timeframe;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DashboardApi - functional programming interface
 */
export const DashboardApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DashboardApiAxiosParamCreator(configuration)
    return {
        /**
         * Calculates the average order value for the specified timeframe.
         * @summary Get average order value (Admin)
         * @param {DashboardAovGetTimeframeEnum} [timeframe] The timeframe filter.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardAovGet(timeframe?: DashboardAovGetTimeframeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardAovGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardAovGet(timeframe, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.dashboardAovGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves total counts for users, stores, orders, and delivered orders.
         * @summary Get dashboard card metrics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardCardsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardCardsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardCardsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.dashboardCardsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves statistics like new customers, new stores, stock status, items sold, and revenue for a specific timeframe.
         * @summary Get dashboard statistics for a timeframe (Admin)
         * @param {DashboardStatsGetTimeframeEnum} [timeframe] The timeframe for the statistics.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardStatsGet(timeframe?: DashboardStatsGetTimeframeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardStatsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardStatsGet(timeframe, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.dashboardStatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a list of recent transactions within the specified timeframe.
         * @summary Get recent transactions (Admin)
         * @param {DashboardTransactionsGetTimeframeEnum} [timeframe] The timeframe filter.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardTransactionsGet(timeframe?: DashboardTransactionsGetTimeframeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardTransactionsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardTransactionsGet(timeframe, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.dashboardTransactionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DashboardApi - factory interface
 */
export const DashboardApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DashboardApiFp(configuration)
    return {
        /**
         * Calculates the average order value for the specified timeframe.
         * @summary Get average order value (Admin)
         * @param {DashboardAovGetTimeframeEnum} [timeframe] The timeframe filter.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardAovGet(timeframe?: DashboardAovGetTimeframeEnum, options?: RawAxiosRequestConfig): AxiosPromise<DashboardAovGet200Response> {
            return localVarFp.dashboardAovGet(timeframe, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves total counts for users, stores, orders, and delivered orders.
         * @summary Get dashboard card metrics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardCardsGet(options?: RawAxiosRequestConfig): AxiosPromise<DashboardCardsGet200Response> {
            return localVarFp.dashboardCardsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves statistics like new customers, new stores, stock status, items sold, and revenue for a specific timeframe.
         * @summary Get dashboard statistics for a timeframe (Admin)
         * @param {DashboardStatsGetTimeframeEnum} [timeframe] The timeframe for the statistics.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardStatsGet(timeframe?: DashboardStatsGetTimeframeEnum, options?: RawAxiosRequestConfig): AxiosPromise<DashboardStatsGet200Response> {
            return localVarFp.dashboardStatsGet(timeframe, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a list of recent transactions within the specified timeframe.
         * @summary Get recent transactions (Admin)
         * @param {DashboardTransactionsGetTimeframeEnum} [timeframe] The timeframe filter.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardTransactionsGet(timeframe?: DashboardTransactionsGetTimeframeEnum, options?: RawAxiosRequestConfig): AxiosPromise<DashboardTransactionsGet200Response> {
            return localVarFp.dashboardTransactionsGet(timeframe, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DashboardApi - object-oriented interface
 */
export class DashboardApi extends BaseAPI {
    /**
     * Calculates the average order value for the specified timeframe.
     * @summary Get average order value (Admin)
     * @param {DashboardAovGetTimeframeEnum} [timeframe] The timeframe filter.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public dashboardAovGet(timeframe?: DashboardAovGetTimeframeEnum, options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardAovGet(timeframe, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves total counts for users, stores, orders, and delivered orders.
     * @summary Get dashboard card metrics (Admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public dashboardCardsGet(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardCardsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves statistics like new customers, new stores, stock status, items sold, and revenue for a specific timeframe.
     * @summary Get dashboard statistics for a timeframe (Admin)
     * @param {DashboardStatsGetTimeframeEnum} [timeframe] The timeframe for the statistics.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public dashboardStatsGet(timeframe?: DashboardStatsGetTimeframeEnum, options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardStatsGet(timeframe, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a list of recent transactions within the specified timeframe.
     * @summary Get recent transactions (Admin)
     * @param {DashboardTransactionsGetTimeframeEnum} [timeframe] The timeframe filter.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public dashboardTransactionsGet(timeframe?: DashboardTransactionsGetTimeframeEnum, options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardTransactionsGet(timeframe, options).then((request) => request(this.axios, this.basePath));
    }
}

export const DashboardAovGetTimeframeEnum = {
    Last7days: 'last7days',
    _7d: '7d',
    Last1month: 'last1month',
    _1m: '1m',
    Last3months: 'last3months',
    _3m: '3m',
    Last1year: 'last1year',
    _1y: '1y'
} as const;
export type DashboardAovGetTimeframeEnum = typeof DashboardAovGetTimeframeEnum[keyof typeof DashboardAovGetTimeframeEnum];
export const DashboardStatsGetTimeframeEnum = {
    Last7days: 'last7days',
    _7d: '7d',
    Last1month: 'last1month',
    _1m: '1m',
    Last3months: 'last3months',
    _3m: '3m',
    Last1year: 'last1year',
    _1y: '1y'
} as const;
export type DashboardStatsGetTimeframeEnum = typeof DashboardStatsGetTimeframeEnum[keyof typeof DashboardStatsGetTimeframeEnum];
export const DashboardTransactionsGetTimeframeEnum = {
    Last7days: 'last7days',
    _7d: '7d',
    Last1month: 'last1month',
    _1m: '1m',
    Last3months: 'last3months',
    _3m: '3m',
    Last1year: 'last1year',
    _1y: '1y'
} as const;
export type DashboardTransactionsGetTimeframeEnum = typeof DashboardTransactionsGetTimeframeEnum[keyof typeof DashboardTransactionsGetTimeframeEnum];
