/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiV1StaffPostRequest } from '../models';
// @ts-ignore
import type { ApiV1StaffStaffIdPatchRequest } from '../models';
/**
 * StaffApi - axios parameter creator
 */
export const StaffApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List all staff members for the authenticated vendor owner
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/staff`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new staff member (shopper) for a vendor
         * @param {ApiV1StaffPostRequest} apiV1StaffPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffPost: async (apiV1StaffPostRequest: ApiV1StaffPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiV1StaffPostRequest' is not null or undefined
            assertParamExists('apiV1StaffPost', 'apiV1StaffPostRequest', apiV1StaffPostRequest)
            const localVarPath = `/api/v1/staff`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiV1StaffPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a staff member\'s account
         * @param {string} staffId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffStaffIdDelete: async (staffId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'staffId' is not null or undefined
            assertParamExists('apiV1StaffStaffIdDelete', 'staffId', staffId)
            const localVarPath = `/api/v1/staff/{staffId}`
                .replace(`{${"staffId"}}`, encodeURIComponent(String(staffId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single staff member by ID
         * @param {string} staffId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffStaffIdGet: async (staffId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'staffId' is not null or undefined
            assertParamExists('apiV1StaffStaffIdGet', 'staffId', staffId)
            const localVarPath = `/api/v1/staff/{staffId}`
                .replace(`{${"staffId"}}`, encodeURIComponent(String(staffId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a staff member\'s details
         * @param {ApiV1StaffStaffIdPatchRequest} apiV1StaffStaffIdPatchRequest 
         * @param {string} staffId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffStaffIdPatch: async (apiV1StaffStaffIdPatchRequest: ApiV1StaffStaffIdPatchRequest, staffId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiV1StaffStaffIdPatchRequest' is not null or undefined
            assertParamExists('apiV1StaffStaffIdPatch', 'apiV1StaffStaffIdPatchRequest', apiV1StaffStaffIdPatchRequest)
            // verify required parameter 'staffId' is not null or undefined
            assertParamExists('apiV1StaffStaffIdPatch', 'staffId', staffId)
            const localVarPath = `/api/v1/staff/{staffId}`
                .replace(`{${"staffId"}}`, encodeURIComponent(String(staffId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiV1StaffStaffIdPatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all staff members for a specific store
         * @param {string} vendorId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffStoreVendorIdGet: async (vendorId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'vendorId' is not null or undefined
            assertParamExists('apiV1StaffStoreVendorIdGet', 'vendorId', vendorId)
            const localVarPath = `/api/v1/staff/store/{vendorId}`
                .replace(`{${"vendorId"}}`, encodeURIComponent(String(vendorId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StaffApi - functional programming interface
 */
export const StaffApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StaffApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List all staff members for the authenticated vendor owner
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StaffGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StaffGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StaffApi.apiV1StaffGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new staff member (shopper) for a vendor
         * @param {ApiV1StaffPostRequest} apiV1StaffPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StaffPost(apiV1StaffPostRequest: ApiV1StaffPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StaffPost(apiV1StaffPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StaffApi.apiV1StaffPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a staff member\'s account
         * @param {string} staffId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StaffStaffIdDelete(staffId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StaffStaffIdDelete(staffId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StaffApi.apiV1StaffStaffIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single staff member by ID
         * @param {string} staffId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StaffStaffIdGet(staffId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StaffStaffIdGet(staffId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StaffApi.apiV1StaffStaffIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a staff member\'s details
         * @param {ApiV1StaffStaffIdPatchRequest} apiV1StaffStaffIdPatchRequest 
         * @param {string} staffId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StaffStaffIdPatch(apiV1StaffStaffIdPatchRequest: ApiV1StaffStaffIdPatchRequest, staffId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StaffStaffIdPatch(apiV1StaffStaffIdPatchRequest, staffId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StaffApi.apiV1StaffStaffIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all staff members for a specific store
         * @param {string} vendorId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StaffStoreVendorIdGet(vendorId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StaffStoreVendorIdGet(vendorId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StaffApi.apiV1StaffStoreVendorIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StaffApi - factory interface
 */
export const StaffApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StaffApiFp(configuration)
    return {
        /**
         * 
         * @summary List all staff members for the authenticated vendor owner
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1StaffGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new staff member (shopper) for a vendor
         * @param {ApiV1StaffPostRequest} apiV1StaffPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffPost(apiV1StaffPostRequest: ApiV1StaffPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1StaffPost(apiV1StaffPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a staff member\'s account
         * @param {string} staffId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffStaffIdDelete(staffId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1StaffStaffIdDelete(staffId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single staff member by ID
         * @param {string} staffId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffStaffIdGet(staffId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1StaffStaffIdGet(staffId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a staff member\'s details
         * @param {ApiV1StaffStaffIdPatchRequest} apiV1StaffStaffIdPatchRequest 
         * @param {string} staffId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffStaffIdPatch(apiV1StaffStaffIdPatchRequest: ApiV1StaffStaffIdPatchRequest, staffId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1StaffStaffIdPatch(apiV1StaffStaffIdPatchRequest, staffId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all staff members for a specific store
         * @param {string} vendorId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StaffStoreVendorIdGet(vendorId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiV1StaffStoreVendorIdGet(vendorId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StaffApi - object-oriented interface
 */
export class StaffApi extends BaseAPI {
    /**
     * 
     * @summary List all staff members for the authenticated vendor owner
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StaffGet(options?: RawAxiosRequestConfig) {
        return StaffApiFp(this.configuration).apiV1StaffGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new staff member (shopper) for a vendor
     * @param {ApiV1StaffPostRequest} apiV1StaffPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StaffPost(apiV1StaffPostRequest: ApiV1StaffPostRequest, options?: RawAxiosRequestConfig) {
        return StaffApiFp(this.configuration).apiV1StaffPost(apiV1StaffPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a staff member\'s account
     * @param {string} staffId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StaffStaffIdDelete(staffId: string, options?: RawAxiosRequestConfig) {
        return StaffApiFp(this.configuration).apiV1StaffStaffIdDelete(staffId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single staff member by ID
     * @param {string} staffId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StaffStaffIdGet(staffId: string, options?: RawAxiosRequestConfig) {
        return StaffApiFp(this.configuration).apiV1StaffStaffIdGet(staffId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a staff member\'s details
     * @param {ApiV1StaffStaffIdPatchRequest} apiV1StaffStaffIdPatchRequest 
     * @param {string} staffId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StaffStaffIdPatch(apiV1StaffStaffIdPatchRequest: ApiV1StaffStaffIdPatchRequest, staffId: string, options?: RawAxiosRequestConfig) {
        return StaffApiFp(this.configuration).apiV1StaffStaffIdPatch(apiV1StaffStaffIdPatchRequest, staffId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all staff members for a specific store
     * @param {string} vendorId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StaffStoreVendorIdGet(vendorId: string, options?: RawAxiosRequestConfig) {
        return StaffApiFp(this.configuration).apiV1StaffStoreVendorIdGet(vendorId, options).then((request) => request(this.axios, this.basePath));
    }
}

