/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateUserPayload } from '../models';
// @ts-ignore
import type { Device } from '../models';
// @ts-ignore
import type { DevicesPostRequest } from '../models';
// @ts-ignore
import type { PaginatedUsers } from '../models';
// @ts-ignore
import type { Role } from '../models';
// @ts-ignore
import type { UpdateUserPayload } from '../models';
// @ts-ignore
import type { User } from '../models';
// @ts-ignore
import type { UsersAdminStatsGet200Response } from '../models';
// @ts-ignore
import type { UsersMeDeleteAccountConfirmPostRequest } from '../models';
// @ts-ignore
import type { UsersMeSettingsPatchRequest } from '../models';
// @ts-ignore
import type { VendorProduct } from '../models';
// @ts-ignore
import type { Verification } from '../models';
/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Unregister a device for push notifications
         * @param {string} fcmToken The FCM token of the device to unregister.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesFcmTokenDelete: async (fcmToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fcmToken' is not null or undefined
            assertParamExists('devicesFcmTokenDelete', 'fcmToken', fcmToken)
            const localVarPath = `/devices/{fcmToken}`
                .replace(`{${"fcmToken"}}`, encodeURIComponent(String(fcmToken)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a device for push notifications
         * @param {DevicesPostRequest} devicesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesPost: async (devicesPostRequest: DevicesPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'devicesPostRequest' is not null or undefined
            assertParamExists('devicesPost', 'devicesPostRequest', devicesPostRequest)
            const localVarPath = `/devices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(devicesPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a list of all vendor-specific products from all stores owned by a particular user. This can be used by an admin or the user themselves.
         * @summary Get all products from all vendors belonging to a user
         * @param {string} userId The ID of the user whose vendor products are to be fetched.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productUserUserIdGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('productUserUserIdGet', 'userId', userId)
            const localVarPath = `/product/user/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Downloads a CSV file containing a list of all admin users.
         * @summary Export list of admins (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminExportGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/admin/export`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deactivate an admin user account (Admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminIdDeactivatePatch: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersAdminIdDeactivatePatch', 'id', id)
            const localVarPath = `/users/admin/{id}/deactivate`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an admin user profile (Admin)
         * @param {UpdateUserPayload} updateUserPayload 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminIdPatch: async (updateUserPayload: UpdateUserPayload, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateUserPayload' is not null or undefined
            assertParamExists('usersAdminIdPatch', 'updateUserPayload', updateUserPayload)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersAdminIdPatch', 'id', id)
            const localVarPath = `/users/admin/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new admin user (Admin)
         * @param {CreateUserPayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminPost: async (body: CreateUserPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('usersAdminPost', 'body', body)
            const localVarPath = `/users/admin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves statistics about admin users, including total count and active count.
         * @summary Get admin statistics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminStatsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/admin/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a paginated list of users
         * @param {boolean} [mobileVerified] Filter by mobile verification status.
         * @param {boolean} [active] Filter by active status.
         * @param {boolean} [online] Filter by online status.
         * @param {Role} [role] Filter by user role.
         * @param {string} [language] Filter by language.
         * @param {number} [page] Page number for pagination.
         * @param {number} [size] Number of items per page.
         * @param {string} [search] Search by name, email, or mobile number.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet: async (mobileVerified?: boolean, active?: boolean, online?: boolean, role?: Role, language?: string, page?: number, size?: number, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (mobileVerified !== undefined) {
                localVarQueryParameter['mobileVerified'] = mobileVerified;
            }

            if (active !== undefined) {
                localVarQueryParameter['active'] = active;
            }

            if (online !== undefined) {
                localVarQueryParameter['online'] = online;
            }

            if (role !== undefined) {
                localVarQueryParameter['role'] = role;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Permanently deletes the user account.  This operation will fail if the user has active orders (orders not in a terminal state). For administrative deletion of other users, admin privileges are required.  For self-deletion, use the authenticated route. 
         * @summary Delete a user
         * @param {string} id The ID of the user to delete. (Must match authenticated user ID unless admin).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdDelete', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a user by their ID
         * @param {string} id The ID of the user to retrieve.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdGet', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Completes the account deletion process using the email OTP.  Upon success, the account is soft-deleted (active: false).  Note: This will fail if the user has active, incomplete orders. 
         * @summary Confirm account deletion for the authenticated user
         * @param {UsersMeDeleteAccountConfirmPostRequest} usersMeDeleteAccountConfirmPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeDeleteAccountConfirmPost: async (usersMeDeleteAccountConfirmPostRequest: UsersMeDeleteAccountConfirmPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'usersMeDeleteAccountConfirmPostRequest' is not null or undefined
            assertParamExists('usersMeDeleteAccountConfirmPost', 'usersMeDeleteAccountConfirmPostRequest', usersMeDeleteAccountConfirmPostRequest)
            const localVarPath = `/users/me/delete-account/confirm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usersMeDeleteAccountConfirmPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Starts the account deletion process by sending a 6-digit One-Time Password (OTP)  to the user\'s registered email address. This OTP must be used in the confirmation endpoint. The request will fail if the user has no registered email. 
         * @summary Initiate account deletion for the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeDeleteAccountInitiatePost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/delete-account/initiate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Allows users to manage their preferences, such as how product replacements are handled and their preferred unit system. 
         * @summary Update authenticated user\'s settings
         * @param {UsersMeSettingsPatchRequest} usersMeSettingsPatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeSettingsPatch: async (usersMeSettingsPatchRequest: UsersMeSettingsPatchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'usersMeSettingsPatchRequest' is not null or undefined
            assertParamExists('usersMeSettingsPatch', 'usersMeSettingsPatchRequest', usersMeSettingsPatchRequest)
            const localVarPath = `/users/me/settings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usersMeSettingsPatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update the authenticated user\'s details
         * @param {UpdateUserPayload} updateUserPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUpdatePut: async (updateUserPayload: UpdateUserPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateUserPayload' is not null or undefined
            assertParamExists('usersUpdatePut', 'updateUserPayload', updateUserPayload)
            const localVarPath = `/users/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves all stored verification codes. Intended for admin/debugging purposes.
         * @summary Get all verification codes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersVerificationCodesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/verificationCodes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Unregister a device for push notifications
         * @param {string} fcmToken The FCM token of the device to unregister.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async devicesFcmTokenDelete(fcmToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.devicesFcmTokenDelete(fcmToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.devicesFcmTokenDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register a device for push notifications
         * @param {DevicesPostRequest} devicesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async devicesPost(devicesPostRequest: DevicesPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Device>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.devicesPost(devicesPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.devicesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a list of all vendor-specific products from all stores owned by a particular user. This can be used by an admin or the user themselves.
         * @summary Get all products from all vendors belonging to a user
         * @param {string} userId The ID of the user whose vendor products are to be fetched.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productUserUserIdGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<VendorProduct>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productUserUserIdGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.productUserUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Downloads a CSV file containing a list of all admin users.
         * @summary Export list of admins (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersAdminExportGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersAdminExportGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersAdminExportGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deactivate an admin user account (Admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersAdminIdDeactivatePatch(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersAdminIdDeactivatePatch(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersAdminIdDeactivatePatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an admin user profile (Admin)
         * @param {UpdateUserPayload} updateUserPayload 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersAdminIdPatch(updateUserPayload: UpdateUserPayload, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersAdminIdPatch(updateUserPayload, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersAdminIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new admin user (Admin)
         * @param {CreateUserPayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersAdminPost(body: CreateUserPayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersAdminPost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersAdminPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves statistics about admin users, including total count and active count.
         * @summary Get admin statistics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersAdminStatsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersAdminStatsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersAdminStatsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersAdminStatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a paginated list of users
         * @param {boolean} [mobileVerified] Filter by mobile verification status.
         * @param {boolean} [active] Filter by active status.
         * @param {boolean} [online] Filter by online status.
         * @param {Role} [role] Filter by user role.
         * @param {string} [language] Filter by language.
         * @param {number} [page] Page number for pagination.
         * @param {number} [size] Number of items per page.
         * @param {string} [search] Search by name, email, or mobile number.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersGet(mobileVerified?: boolean, active?: boolean, online?: boolean, role?: Role, language?: string, page?: number, size?: number, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedUsers>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersGet(mobileVerified, active, online, role, language, page, size, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Permanently deletes the user account.  This operation will fail if the user has active orders (orders not in a terminal state). For administrative deletion of other users, admin privileges are required.  For self-deletion, use the authenticated route. 
         * @summary Delete a user
         * @param {string} id The ID of the user to delete. (Must match authenticated user ID unless admin).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a user by their ID
         * @param {string} id The ID of the user to retrieve.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Completes the account deletion process using the email OTP.  Upon success, the account is soft-deleted (active: false).  Note: This will fail if the user has active, incomplete orders. 
         * @summary Confirm account deletion for the authenticated user
         * @param {UsersMeDeleteAccountConfirmPostRequest} usersMeDeleteAccountConfirmPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeDeleteAccountConfirmPost(usersMeDeleteAccountConfirmPostRequest: UsersMeDeleteAccountConfirmPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeDeleteAccountConfirmPost(usersMeDeleteAccountConfirmPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeDeleteAccountConfirmPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Starts the account deletion process by sending a 6-digit One-Time Password (OTP)  to the user\'s registered email address. This OTP must be used in the confirmation endpoint. The request will fail if the user has no registered email. 
         * @summary Initiate account deletion for the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeDeleteAccountInitiatePost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeDeleteAccountInitiatePost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeDeleteAccountInitiatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Allows users to manage their preferences, such as how product replacements are handled and their preferred unit system. 
         * @summary Update authenticated user\'s settings
         * @param {UsersMeSettingsPatchRequest} usersMeSettingsPatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeSettingsPatch(usersMeSettingsPatchRequest: UsersMeSettingsPatchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeSettingsPatch(usersMeSettingsPatchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeSettingsPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update the authenticated user\'s details
         * @param {UpdateUserPayload} updateUserPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersUpdatePut(updateUserPayload: UpdateUserPayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersUpdatePut(updateUserPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersUpdatePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves all stored verification codes. Intended for admin/debugging purposes.
         * @summary Get all verification codes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersVerificationCodesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Verification>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersVerificationCodesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersVerificationCodesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Unregister a device for push notifications
         * @param {string} fcmToken The FCM token of the device to unregister.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesFcmTokenDelete(fcmToken: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.devicesFcmTokenDelete(fcmToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a device for push notifications
         * @param {DevicesPostRequest} devicesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        devicesPost(devicesPostRequest: DevicesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<Device> {
            return localVarFp.devicesPost(devicesPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a list of all vendor-specific products from all stores owned by a particular user. This can be used by an admin or the user themselves.
         * @summary Get all products from all vendors belonging to a user
         * @param {string} userId The ID of the user whose vendor products are to be fetched.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productUserUserIdGet(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<VendorProduct>> {
            return localVarFp.productUserUserIdGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Downloads a CSV file containing a list of all admin users.
         * @summary Export list of admins (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminExportGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersAdminExportGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deactivate an admin user account (Admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminIdDeactivatePatch(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersAdminIdDeactivatePatch(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an admin user profile (Admin)
         * @param {UpdateUserPayload} updateUserPayload 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminIdPatch(updateUserPayload: UpdateUserPayload, id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersAdminIdPatch(updateUserPayload, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new admin user (Admin)
         * @param {CreateUserPayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminPost(body: CreateUserPayload, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersAdminPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves statistics about admin users, including total count and active count.
         * @summary Get admin statistics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAdminStatsGet(options?: RawAxiosRequestConfig): AxiosPromise<UsersAdminStatsGet200Response> {
            return localVarFp.usersAdminStatsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a paginated list of users
         * @param {boolean} [mobileVerified] Filter by mobile verification status.
         * @param {boolean} [active] Filter by active status.
         * @param {boolean} [online] Filter by online status.
         * @param {Role} [role] Filter by user role.
         * @param {string} [language] Filter by language.
         * @param {number} [page] Page number for pagination.
         * @param {number} [size] Number of items per page.
         * @param {string} [search] Search by name, email, or mobile number.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet(mobileVerified?: boolean, active?: boolean, online?: boolean, role?: Role, language?: string, page?: number, size?: number, search?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedUsers> {
            return localVarFp.usersGet(mobileVerified, active, online, role, language, page, size, search, options).then((request) => request(axios, basePath));
        },
        /**
         * Permanently deletes the user account.  This operation will fail if the user has active orders (orders not in a terminal state). For administrative deletion of other users, admin privileges are required.  For self-deletion, use the authenticated route. 
         * @summary Delete a user
         * @param {string} id The ID of the user to delete. (Must match authenticated user ID unless admin).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a user by their ID
         * @param {string} id The ID of the user to retrieve.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.usersIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Completes the account deletion process using the email OTP.  Upon success, the account is soft-deleted (active: false).  Note: This will fail if the user has active, incomplete orders. 
         * @summary Confirm account deletion for the authenticated user
         * @param {UsersMeDeleteAccountConfirmPostRequest} usersMeDeleteAccountConfirmPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeDeleteAccountConfirmPost(usersMeDeleteAccountConfirmPostRequest: UsersMeDeleteAccountConfirmPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersMeDeleteAccountConfirmPost(usersMeDeleteAccountConfirmPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Starts the account deletion process by sending a 6-digit One-Time Password (OTP)  to the user\'s registered email address. This OTP must be used in the confirmation endpoint. The request will fail if the user has no registered email. 
         * @summary Initiate account deletion for the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeDeleteAccountInitiatePost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersMeDeleteAccountInitiatePost(options).then((request) => request(axios, basePath));
        },
        /**
         * Allows users to manage their preferences, such as how product replacements are handled and their preferred unit system. 
         * @summary Update authenticated user\'s settings
         * @param {UsersMeSettingsPatchRequest} usersMeSettingsPatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeSettingsPatch(usersMeSettingsPatchRequest: UsersMeSettingsPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.usersMeSettingsPatch(usersMeSettingsPatchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update the authenticated user\'s details
         * @param {UpdateUserPayload} updateUserPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUpdatePut(updateUserPayload: UpdateUserPayload, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.usersUpdatePut(updateUserPayload, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves all stored verification codes. Intended for admin/debugging purposes.
         * @summary Get all verification codes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersVerificationCodesGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Verification>> {
            return localVarFp.usersVerificationCodesGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Unregister a device for push notifications
     * @param {string} fcmToken The FCM token of the device to unregister.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public devicesFcmTokenDelete(fcmToken: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).devicesFcmTokenDelete(fcmToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register a device for push notifications
     * @param {DevicesPostRequest} devicesPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public devicesPost(devicesPostRequest: DevicesPostRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).devicesPost(devicesPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a list of all vendor-specific products from all stores owned by a particular user. This can be used by an admin or the user themselves.
     * @summary Get all products from all vendors belonging to a user
     * @param {string} userId The ID of the user whose vendor products are to be fetched.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productUserUserIdGet(userId: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).productUserUserIdGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Downloads a CSV file containing a list of all admin users.
     * @summary Export list of admins (Admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersAdminExportGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersAdminExportGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deactivate an admin user account (Admin)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersAdminIdDeactivatePatch(id: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersAdminIdDeactivatePatch(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an admin user profile (Admin)
     * @param {UpdateUserPayload} updateUserPayload 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersAdminIdPatch(updateUserPayload: UpdateUserPayload, id: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersAdminIdPatch(updateUserPayload, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new admin user (Admin)
     * @param {CreateUserPayload} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersAdminPost(body: CreateUserPayload, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersAdminPost(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves statistics about admin users, including total count and active count.
     * @summary Get admin statistics (Admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersAdminStatsGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersAdminStatsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a paginated list of users
     * @param {boolean} [mobileVerified] Filter by mobile verification status.
     * @param {boolean} [active] Filter by active status.
     * @param {boolean} [online] Filter by online status.
     * @param {Role} [role] Filter by user role.
     * @param {string} [language] Filter by language.
     * @param {number} [page] Page number for pagination.
     * @param {number} [size] Number of items per page.
     * @param {string} [search] Search by name, email, or mobile number.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersGet(mobileVerified?: boolean, active?: boolean, online?: boolean, role?: Role, language?: string, page?: number, size?: number, search?: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersGet(mobileVerified, active, online, role, language, page, size, search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Permanently deletes the user account.  This operation will fail if the user has active orders (orders not in a terminal state). For administrative deletion of other users, admin privileges are required.  For self-deletion, use the authenticated route. 
     * @summary Delete a user
     * @param {string} id The ID of the user to delete. (Must match authenticated user ID unless admin).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a user by their ID
     * @param {string} id The ID of the user to retrieve.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersIdGet(id: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Completes the account deletion process using the email OTP.  Upon success, the account is soft-deleted (active: false).  Note: This will fail if the user has active, incomplete orders. 
     * @summary Confirm account deletion for the authenticated user
     * @param {UsersMeDeleteAccountConfirmPostRequest} usersMeDeleteAccountConfirmPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeDeleteAccountConfirmPost(usersMeDeleteAccountConfirmPostRequest: UsersMeDeleteAccountConfirmPostRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeDeleteAccountConfirmPost(usersMeDeleteAccountConfirmPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Starts the account deletion process by sending a 6-digit One-Time Password (OTP)  to the user\'s registered email address. This OTP must be used in the confirmation endpoint. The request will fail if the user has no registered email. 
     * @summary Initiate account deletion for the authenticated user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeDeleteAccountInitiatePost(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeDeleteAccountInitiatePost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Allows users to manage their preferences, such as how product replacements are handled and their preferred unit system. 
     * @summary Update authenticated user\'s settings
     * @param {UsersMeSettingsPatchRequest} usersMeSettingsPatchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeSettingsPatch(usersMeSettingsPatchRequest: UsersMeSettingsPatchRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeSettingsPatch(usersMeSettingsPatchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update the authenticated user\'s details
     * @param {UpdateUserPayload} updateUserPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersUpdatePut(updateUserPayload: UpdateUserPayload, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersUpdatePut(updateUserPayload, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves all stored verification codes. Intended for admin/debugging purposes.
     * @summary Get all verification codes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersVerificationCodesGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersVerificationCodesGet(options).then((request) => request(this.axios, this.basePath));
    }
}

