/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AuthRegisterPostRequest {
    /**
     * The user\'s full name.
     */
    'name': string;
    /**
     * The user\'s email address.
     */
    'email': string;
    /**
     * The user\'s mobile number in E.164 format.
     */
    'mobileNumber': string;
    /**
     * The role for the new user.
     */
    'role': AuthRegisterPostRequestRoleEnum;
    /**
     * Required if role is \'store_shopper\'. The ID of the vendor this staff member belongs to.
     */
    'vendorId'?: string;
}

export const AuthRegisterPostRequestRoleEnum = {
    Customer: 'customer',
    Vendor: 'vendor',
    StoreAdmin: 'store_admin',
    StoreShopper: 'store_shopper',
    DeliveryPerson: 'delivery_person',
    Admin: 'admin'
} as const;

export type AuthRegisterPostRequestRoleEnum = typeof AuthRegisterPostRequestRoleEnum[keyof typeof AuthRegisterPostRequestRoleEnum];


