/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Category {
    'id'?: string;
    'name'?: string;
    'description'?: string | null;
    'parentId'?: string | null;
    'type'?: CategoryTypeEnum;
    'imageUrl'?: string | null;
    'createdAt'?: string;
    'updatedAt'?: string;
}

export const CategoryTypeEnum = {
    Product: 'PRODUCT',
    Service: 'SERVICE'
} as const;

export type CategoryTypeEnum = typeof CategoryTypeEnum[keyof typeof CategoryTypeEnum];


