/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RatingType } from './rating-type';

export interface CreateRatingPayload {
    /**
     * The ID of the order being rated (Optional depending on the rating type).
     */
    'orderId'?: string | null;
    /**
     * The rating score from 1 to 5.
     */
    'rating': number;
    /**
     * An optional comment for the rating.
     */
    'comment'?: string | null;
    'type': RatingType;
    /**
     * Required if type is VENDOR.
     */
    'ratedVendorId'?: string;
    /**
     * Required if type is SHOPPER, DELIVERER, or USER.
     */
    'ratedUserId'?: string;
    /**
     * Required if type is PRODUCT.
     */
    'ratedProductId'?: string;
}



