/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateCategoryPayload {
    'name': string;
    /**
     * The ID of the parent category, if this is a sub-category.
     */
    'parentId'?: string | null;
    'type': CreateCategoryPayloadTypeEnum;
    'imageUrl'?: string | null;
}

export const CreateCategoryPayloadTypeEnum = {
    Product: 'PRODUCT',
    Service: 'SERVICE'
} as const;

export type CreateCategoryPayloadTypeEnum = typeof CreateCategoryPayloadTypeEnum[keyof typeof CreateCategoryPayloadTypeEnum];


