/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateVendorProductWithBarcodePayload {
    'vendorId': string;
    'barcode': string;
    'price': number;
    'name': string;
    'description'?: string | null;
    'categoryIds': Array<string>;
    'discountedPrice'?: number | null;
    'sku'?: string | null;
    /**
     * Array of image URLs or base64 encoded strings.
     */
    'images'?: Array<string>;
    'stock'?: number | null;
    'isAvailable'?: boolean;
    'attributes'?: { [key: string]: any; };
    'tagIds'?: Array<string> | null;
}

