/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DeliverySlotTimeSlotsInner {
    /**
     * The start time of the slot in UTC (ISO 8601 format).
     */
    'start'?: string;
    /**
     * The end time of the slot in UTC (ISO 8601 format).
     */
    'end'?: string;
    /**
     * The user-friendly display string in the vendor\'s local time.
     */
    'display'?: string;
}

