/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeliveryAddress } from './delivery-address';
// May contain unused imports in some cases
// @ts-ignore
import type { DeliveryMethod } from './delivery-method';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemWithRelations } from './order-item-with-relations';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderStatus } from './order-status';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethods } from './payment-methods';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentStatus } from './payment-status';
// May contain unused imports in some cases
// @ts-ignore
import type { ShoppingMethod } from './shopping-method';
// May contain unused imports in some cases
// @ts-ignore
import type { UserSummary } from './user-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { VendorWithDetails } from './vendor-with-details';

export interface OrderWithRelations {
    'id'?: string;
    'userId'?: string;
    'vendorId'?: string;
    'orderCode'?: string;
    'pickupOtp'?: string | null;
    'subtotal'?: number;
    'totalAmount'?: number;
    'deliveryFee'?: number | null;
    'serviceFee'?: number | null;
    'shoppingFee'?: number | null;
    'shopperTip'?: number | null;
    'deliveryPersonTip'?: number | null;
    'paymentMethod'?: PaymentMethods;
    'paymentStatus'?: PaymentStatus;
    'orderStatus'?: OrderStatus;
    'deliveryAddressId'?: string | null;
    'deliveryInstructions'?: string | null;
    'shopperId'?: string | null;
    'deliveryPersonId'?: string | null;
    'shoppingMethod'?: ShoppingMethod;
    'deliveryMethod'?: DeliveryMethod;
    'shoppingStartTime'?: string | null;
    'scheduledDeliveryTime'?: string | null;
    'actualDeliveryTime'?: string | null;
    'pickupOtpVerifiedAt'?: string | null;
    'reasonForDecline'?: string | null;
    'createdAt'?: string;
    'updatedAt'?: string;
    'user'?: UserSummary;
    'shopper'?: UserSummary;
    'deliveryPerson'?: UserSummary;
    'orderItems'?: Array<OrderItemWithRelations>;
    'vendor'?: VendorWithDetails;
    'deliveryAddress'?: DeliveryAddress;
}



