/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const OrderStatus = {
    Pending: 'pending',
    AcceptedForShopping: 'accepted_for_shopping',
    CurrentlyShopping: 'currently_shopping',
    ReadyForPickup: 'ready_for_pickup',
    ReadyForDelivery: 'ready_for_delivery',
    AcceptedForDelivery: 'accepted_for_delivery',
    EnRoute: 'en_route',
    Delivered: 'delivered',
    PickedUpByCustomer: 'picked_up_by_customer',
    DeclinedByVendor: 'declined_by_vendor',
    CancelledByCustomer: 'cancelled_by_customer'
} as const;

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];



