/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductVendorTransferPost200ResponseDetailsInner } from './product-vendor-transfer-post200-response-details-inner';

export interface ProductVendorTransferPost200Response {
    'successfulTransfers'?: number;
    'skippedTransfers'?: number;
    'details'?: Array<ProductVendorTransferPost200ResponseDetailsInner>;
}

