/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Vendor } from './vendor';
// May contain unused imports in some cases
// @ts-ignore
import type { VendorProduct } from './vendor-product';

export interface StoreWithLimitedProducts {
    'store'?: Vendor;
    'products'?: Array<VendorProduct>;
    /**
     * The total number of products found in the store that match the search criteria.
     */
    'totalProducts'?: number;
}

