/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TransactionSource } from './transaction-source';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionStatus } from './transaction-status';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionType } from './transaction-type';

export interface Transaction {
    'id'?: string;
    'userId'?: string;
    'amount'?: number;
    'type'?: TransactionType;
    'source'?: TransactionSource;
    'status'?: TransactionStatus;
    'description'?: string | null;
    'orderId'?: string;
    /**
     * ID from the external payment provider (e.g., Stripe Payment Intent ID).
     */
    'externalId'?: string | null;
    /**
     * Additional metadata, such as payment details from Stripe.
     */
    'meta'?: object | null;
    'createdAt'?: string;
    'updatedAt'?: string;
}

