/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface TransactionsCreatePaymentIntentPostRequest {
    /**
     * Optional. The specific amount to charge for this payment intent. If not provided, the full order budget will be used. Useful for partial payments (e.g., EBT).
     */
    'amount'?: number | null;
    'orderId': string;
    /**
     * Optional. Specifies the type of payment. Use \'ebt\' to configure the intent for EBT processing, otherwise defaults to standard automatic payment methods.
     */
    'paymentType'?: TransactionsCreatePaymentIntentPostRequestPaymentTypeEnum;
}

export const TransactionsCreatePaymentIntentPostRequestPaymentTypeEnum = {
    Card: 'card',
    Ebt: 'ebt'
} as const;

export type TransactionsCreatePaymentIntentPostRequestPaymentTypeEnum = typeof TransactionsCreatePaymentIntentPostRequestPaymentTypeEnum[keyof typeof TransactionsCreatePaymentIntentPostRequestPaymentTypeEnum];


