/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const TransactionType = {
    OrderPayment: 'ORDER_PAYMENT',
    Refund: 'REFUND',
    VendorPayout: 'VENDOR_PAYOUT',
    DeliveryPayout: 'DELIVERY_PAYOUT',
    TipPayout: 'TIP_PAYOUT',
    PlatformFeeCollected: 'PLATFORM_FEE_COLLECTED',
    WalletTopUp: 'WALLET_TOP_UP',
    Debit: 'DEBIT',
    Credit: 'CREDIT'
} as const;

export type TransactionType = typeof TransactionType[keyof typeof TransactionType];



