/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateVendorProductPayload {
    'price'?: number;
    'discountedPrice'?: number | null;
    'sku'?: string | null;
    'images'?: Array<string>;
    'stock'?: number | null;
    'isAvailable'?: boolean;
    'attributes'?: { [key: string]: any; } | null;
    'name'?: string;
    'description'?: string | null;
    'categoryIds'?: Array<string>;
    'tagIds'?: Array<string>;
    /**
     * The actual price to be paid (prioritizes discountedPrice).
     */
    'effectivePrice'?: number;
    'weight'?: number | null;
    'weightUnit'?: string | null;
    'published'?: boolean;
    'isAlcohol'?: boolean;
    'isPerishable'?: boolean;
    'isAgeRestricted'?: boolean;
    'isEbtEligible'?: boolean;
    'meta'?: object | null;
}

