/* tslint:disable */
/* eslint-disable */
/**
 * PardoMart Node API
 * API documentation for the PardoMart Node.js application.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pardomart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeliveryMethod } from './delivery-method';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderStatus } from './order-status';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethods } from './payment-methods';
// May contain unused imports in some cases
// @ts-ignore
import type { ShoppingMethod } from './shopping-method';

export interface UpdateOrderPayload {
    'totalAmount'?: number;
    'deliveryFee'?: number;
    'serviceFee'?: number;
    'shoppingFee'?: number;
    'paymentMethod'?: PaymentMethods;
    'paymentStatus'?: UpdateOrderPayloadPaymentStatusEnum;
    'orderStatus'?: OrderStatus;
    'deliveryAddressId'?: string;
    'deliveryInstructions'?: string;
    'shoppingHandlerId'?: string;
    'deliveryPersonId'?: string;
    'shoppingMethod'?: ShoppingMethod;
    'deliveryMethod'?: DeliveryMethod;
    'scheduledShoppingStartTime'?: string;
}

export const UpdateOrderPayloadPaymentStatusEnum = {
    Pending: 'pending',
    Paid: 'paid',
    Failed: 'failed'
} as const;

export type UpdateOrderPayloadPaymentStatusEnum = typeof UpdateOrderPayloadPaymentStatusEnum[keyof typeof UpdateOrderPayloadPaymentStatusEnum];


